
/* --------------------Questions With Queries Answer------------------ */

          /* -------- Easy Level ----------- */

/*  1) Calculate Total Number of Vehicles Sold by State  */

    SELECT StateName, SUM(QuantitySold) AS TotalVehiclesSold
    FROM ElectricVehicleSales
    JOIN States ON ElectricVehicleSales.StateID = States.StateID
    GROUP BY StateName;

/*  2) Calculate Average Sales Price of Vehicles in Each State  */

    SELECT StateName, AVG(SalePrice) AS AverageSalePrice
    FROM ElectricVehicleSales
    JOIN States ON ElectricVehicleSales.StateID = States.StateID
    GROUP BY StateName;

/*  3) Find List of Manufacturers and their Vehicles  */

    SELECT ManufacturerName, Model
    FROM Manufacturers
    JOIN Vehicles ON Manufacturers.ManufacturerID = Vehicles.ManufacturerID;

/*  4) Calculate Sales Quantity for a Specific Vehicle  */

    SELECT Model, SUM(QuantitySold) AS TotalSales
    FROM ElectricVehicleSales
    JOIN Vehicles ON ElectricVehicleSales.VehicleID = Vehicles.VehicleID
    WHERE Model = 'Tesla Model 3'
    GROUP BY Model;

/*  5) Calculate Number of Vehicles Sold by Region  */

    SELECT Region, SUM(QuantitySold) AS TotalSales
    FROM ElectricVehicleSales
    JOIN States ON ElectricVehicleSales.StateID = States.StateID
    GROUP BY Region;

	 /* -------- Medium Level ----------- */

/*  6) Find Top 5 States by Total Vehicle Sales  */

    SELECT TOP 5 StateName, SUM(QuantitySold) AS TotalSales
    FROM ElectricVehicleSales
    JOIN States ON ElectricVehicleSales.StateID = States.StateID
    GROUP BY StateName
    ORDER BY TotalSales DESC;

/*  7) Calculate Total Revenue Generated by Each Manufacturer  */ 

    SELECT ManufacturerName, SUM(SalePrice * QuantitySold) AS TotalRevenue
    FROM ElectricVehicleSales
    JOIN Vehicles ON ElectricVehicleSales.VehicleID = Vehicles.VehicleID
    JOIN Manufacturers ON Vehicles.ManufacturerID = Manufacturers.ManufacturerID
    GROUP BY ManufacturerName;

/*  8) Calculate Average Sales per Month for Each Vehicle  */

    SELECT Model, AVG(QuantitySold) AS AverageSalesPerMonth
    FROM ElectricVehicleSales
    JOIN Vehicles ON ElectricVehicleSales.VehicleID = Vehicles.VehicleID
    GROUP BY Model;

/*  9) Calculate Sales by State and Vehicle Type  */
  
    SELECT StateName, VehicleType, SUM(QuantitySold) AS SalesQuantity
    FROM ElectricVehicleSales
    JOIN States ON ElectricVehicleSales.StateID = States.StateID
    JOIN Vehicles ON ElectricVehicleSales.VehicleID = Vehicles.VehicleID
    GROUP BY StateName, VehicleType
    ORDER BY SalesQuantity DESC;

/*  10) Calculate Average Price Of EV by Manufacturer  */

    SELECT Manufacturers.ManufacturerName,AVG(Vehicles.Price) AS AverageVehiclePrice
    FROM Vehicles 
    JOIN Manufacturers ON Vehicles.ManufacturerID = Manufacturers.ManufacturerID
    GROUP BY Manufacturers.ManufacturerName;

	 /* -------- Advance Level ----------- */

/*  11) Find Top 3 States with the Highest Average Vehicle Price  */

    SELECT TOP 3 StateName, AVG(SalePrice) AS AveragePrice
    FROM ElectricVehicleSales
    JOIN States ON ElectricVehicleSales.StateID = States.StateID
    GROUP BY StateName
    ORDER BY AveragePrice DESC;

/*  12) Find Most Popular Vehicle by Region  */

    SELECT Region, Model, SUM(QuantitySold) AS TotalSales
    FROM ElectricVehicleSales
    JOIN States ON ElectricVehicleSales.StateID = States.StateID
    JOIN Vehicles ON ElectricVehicleSales.VehicleID = Vehicles.VehicleID
    GROUP BY Region, Model
    ORDER BY TotalSales DESC;

/*  13) Calculate Vehicle Sales Correlation with State Population  */
   
    SELECT StateName, SUM(QuantitySold) AS TotalSales, Population, 
       SUM(QuantitySold) * 1.0 / Population AS SalesPerCapita
    FROM ElectricVehicleSales
    JOIN States ON ElectricVehicleSales.StateID = States.StateID
    GROUP BY StateName, Population;

/*  14) Get The TOP 10 Vehicle Model With Highest Sales Quantity and Price in 2024  */

    SELECT V.MODEL, EV.QUANTITYSOLD , SUM(EV.QUANTITYSOLD * SALEPRICE) AS TOTALSALES
    FROM ElectricVehicleSales AS EV
    JOIN Vehicles AS V 
    ON EV.VehicleID = V.VehicleID
    WHERE YEAR (EV.SALESDATE) = 2024
    GROUP BY V.Model , EV.QuantitySold
    ORDER BY TOTALSALES DESC;

/*  15) Get The State With The Highest Average Price For EVS Sales in 2024  */

    SELECT TOP 1 S.STATENAME, AVG(EV.SALEPRICE) AS AVERAGE_PRICE
    FROM ElectricVehicleSales  AS EV
    JOIN STATES AS S
    ON EV.StateID = S.StateID
    WHERE YEAR(SALESDATE)=2024 
    GROUP BY S.STATENAME
    ORDER BY AVERAGE_PRICE DESC;